### ISSUE TITLE
uhh L06 Server 

### ISSUE THREAD

**Issue by obiwan1337** [MarkusDamm/EIA-2.1#1]
Deine Aufgabe schmeißt eine Warnung nach dem Laden und dann haut es dir einen Error um die Ohren, weil kein Geburtsdatum eingetragen wurde lul. 
Die Aufzählung bräuchte noch CSS. Du fauli :p 
Wieder kein Konzept.
good luck out there

**Comment by MarkusDamm** [comment]
Thank you für die Hinweise 😅 
Also auf Chrome (für das es angepasst wurde) kommt beim Laden keine Warnung. Ist das eine bezüglich der RAM-Nutzung? Wenn ja soll es so sein ^^
Um das Datumsproblem kümmere ich mich mal noch irgendwann, die anderen Sachen sind definitiv, ganz klar und ohne Zweifel ganz sicher so beabsichtigt. 
good looks out there
