### ISSUE TITLE
l07 Datenbank 

### ISSUE THREAD

**Issue by obiwan1337** [MarkusDamm/EIA-2.1#2]
Also ich sehe schon alle anderen die das Versuchen von dir kopieren easy. 
Netter Editor, kein Error mehr. Leider keine Laute für den Barden 'schnief'.
Hat trotzdem Spass gemacht einen char anzufertigen :grin: 
Datenbank wird angesteuert und auch die Infos werden beim Abrufen auf der Page angezeigt.

**Comment by MarkusDamm** [comment]
Schön zu hören, aber viel wichtiger ist doch, ob Sai'qu dafür sorgen wird, dass ich für die Aufgabe einen :star: bekomme?
