### ISSUE TITLE
L08 canvas

### ISSUE THREAD

**Issue by obiwan1337** [MarkusDamm/EIA-2.1#3]
Mal wieder kein Konzept.
Schlimm mit dir dude.
Eine nette Winterlandschaft  hast gemacht
Nette Iglus und die zwei Türme sind auch sehr LotR.
Aber dein Vogelhaus ist nicht perspektivisch -> Das gibt Abzug der B-Note.
Dazu kommt das Ignorieren von Responsiveness und so. Da ist die R-Note aber unter Null. :p

**Comment by MarkusDamm** [comment]
Schade
